/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.pa1.parcial3.aplicacion;

import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author uth
 */
public class frmEjemploHilos extends javax.swing.JFrame {

    /**
     * Creates new form frmEjemploHilos
     */
    public frmEjemploHilos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblComponente = new javax.swing.JLabel();
        lblCoordenadas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        lblComponente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hn/uth/pa1/parcial3/aplicacion/coche_azul.png"))); // NOI18N
        lblComponente.setText("jLabel1");
        lblComponente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblComponenteKeyPressed(evt);
            }
        });

        lblCoordenadas.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCoordenadas)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(lblComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1320, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 611, Short.MAX_VALUE)
                .addComponent(lblCoordenadas)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblComponenteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblComponenteKeyPressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "hola mundo_ " + evt.getKeyCode());

    }//GEN-LAST:event_lblComponenteKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog
        (this, "hola mundo_ "+evt.getKeyCode());
        if (evt.getKeyCode() == 37) {
            moverIzq(lblComponente);
        }
        if (evt.getKeyCode() == 39) {
            moverDer(lblComponente);
        }
        if (evt.getKeyCode()== 32) {
            ComponenteHilo hilo
                    =new ComponenteHilo
                    ("pa1", lblComponente);
            hilo.start();
        }
    }//GEN-LAST:event_formKeyPressed

    public void moverIzq(JComponent componente) {
        cambiarY(componente, -10);

    }

    public void moverDer(JComponent componente) {
        cambiarY(componente, +10);
    }

    public void cambiarY(JComponent componente,
             int grado
    ) {
        int x = componente.getLocation().x + grado;
        int y = componente.getLocation().y;
        componente.setLocation(x, y);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEjemploHilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEjemploHilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEjemploHilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEjemploHilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEjemploHilos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblComponente;
    private javax.swing.JLabel lblCoordenadas;
    // End of variables declaration//GEN-END:variables
}
